Back to netatalk 2.0.5 for now.

diff --git a/build/ports/netatalk/files/patch-config_Makefile.in b/build/ports/netatalk/files/patch-config_Makefile.in
--- a/build/ports/netatalk/files/patch-config_Makefile.in
+++ b/build/ports/netatalk/files/patch-config_Makefile.in
@@ -1,17 +1,6 @@
---- config/Makefile.in.orig	2010-10-15 06:10:05.000000000 -0400
-+++ config/Makefile.in	2010-11-07 18:38:03.000000000 -0500
-@@ -592,8 +592,8 @@ install-data-local: install-config-files
- 
- uninstall-local:
- 	for f in $(CONFFILES) $(GENFILES); do \
--		echo rm -f $(DESTDIR)$(pkgconfdir)/$$f; \
--		rm -f $(DESTDIR)$(pkgconfdir)/$$f; \
-+		echo rm -f $(DESTDIR)$(pkgconfdir)/$$f.dist; \
-+		rm -f $(DESTDIR)$(pkgconfdir)/$$f.dist; \
- 	done
- 
- @USE_DEBIAN_TRUE@	rm -f $(DESTDIR)/etc/default/netatalk;
-@@ -601,12 +601,8 @@ uninstall-local:
+--- config/Makefile.in.orig	Mon Mar 22 19:22:45 2004
++++ config/Makefile.in	Sat Jun  5 22:08:04 2004
+@@ -386,22 +386,11 @@
  install-config-files: $(CONFFILES) $(GENFILES)
  	$(mkinstalldirs) $(DESTDIR)$(pkgconfdir)
  	for f in $(CONFFILES) $(GENFILES); do \
@@ -21,8 +10,18 @@
 -		else \
 -			echo "not overwriting $$f"; \
 -		fi; \
-+	    echo "$(INSTALL_DATA) $$f $(DESTDIR)$(pkgconfdir)/$$f.dist"; \
-+	    $(INSTALL_DATA) $$f $(DESTDIR)$(pkgconfdir)/$$f.dist; \
++		echo "$(INSTALL_DATA) $$f $(DESTDIR)$(pkgconfdir)/$$f.dist"; \
++		$(INSTALL_DATA) $$f $(DESTDIR)$(pkgconfdir)/$$f.dist; \
  	done
  
- @USE_DEBIAN_TRUE@	$(mkinstalldirs) $(DESTDIR)/default
+ @USE_PAM_TRUE@install-data-local: install-config-files $(PAMFILES)
+-@USE_PAM_TRUE@	$(mkinstalldirs) $(DESTDIR)$(pamdir)
+-@USE_PAM_TRUE@	if test "x$(OVERWRITE_CONFIG)" = "xyes" -o ! -f $(DESTDIR)$(pamdir)/netatalk; then \
+-@USE_PAM_TRUE@	    echo "$(INSTALL_DATA) $$f $(DESTDIR)$(pamdir)/netatalk"; \
+-@USE_PAM_TRUE@	    $(INSTALL_DATA) netatalk.pamd $(DESTDIR)$(pamdir)/netatalk || echo "WARNING: Can't install PAM files";		\
+-@USE_PAM_TRUE@	else \
+-@USE_PAM_TRUE@	    echo "not overwriting $(DESTDIR)$(pamdir)/netatalk"; \
+-@USE_PAM_TRUE@	fi; 
+ 
+ @USE_PAM_FALSE@install-data-local: install-config-files
+ # Tell versions [3.59,3.63) of GNU make to not export all variables.
