Add fsck on root file system for 'full' installation.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -4,6 +4,9 @@
 # $FreeBSD: src/etc/rc.d/fsck,v 1.10 2004/10/07 13:55:25 mtm Exp $
 #
 # Modified by Volker Theile (votdev@gmx.de)
+# Changes:
+# - Refactor fsck_start to process configured disks only
+# - Add fsck_start_root to check root file system on 'full' installations
 #
 
 # PROVIDE: fsck
@@ -15,8 +18,10 @@
 . /etc/configxml.subr
 
 name="fsck"
+extra_commands="root"
 start_cmd="fsck_start"
 stop_cmd=":"
+root_cmd="fsck_start_root"
 
 stop_boot()
 {
@@ -31,7 +36,7 @@ stop_boot()
 
 fsck_start()
 {
-	# Initialize disks.
+	# Initialize disks
 	eval /etc/rc.d.php/disks_init
 
 	if [ "$autoboot" = no ]; then
@@ -52,17 +57,17 @@ fsck_start()
 			-i "position() != last()" -n -b \
 			${configxml_file} | /usr/local/bin/xml unesc | \
 		while read _fstype _devicespecialfile _mdisk _fsck; do
-			# Check if fsck is enabled.
+			# Check if fsck is enabled
 			if [ "0" = "${_fsck}" ]; then
 				continue
 			fi
 
-			# Check if block device exists.
+			# Check if block device exists
 			if [ ! -e "${_devicespecialfile}" ]; then
 				continue
 			fi
 
-			# Skip encrypted disks.
+			# Skip encrypted disks
 			_encrypted=`configxml_get_count "//geli/vdisk[devicespecialfile = '${_mdisk}']"`
 			if [ 0 -lt ${_encrypted} ]; then
 				continue
@@ -117,6 +122,59 @@ fsck_start()
 			esac
 		done
 	fi
+}
+
+fsck_start_root()
+{
+	fsck_y_enable=yes
+
+	# During fsck ignore SIGQUIT
+	trap : 3
+
+	echo "Starting root file system check:"
+	fsck -p
+
+	case $? in
+	0)
+		;;
+	2)
+		stop_boot
+		;;
+	4)
+		echo "Rebooting..."
+		reboot
+		echo "Reboot failed; help!"
+		stop_boot
+		;;
+	8)
+		if checkyesno fsck_y_enable; then
+			echo "File system preen failed, trying fsck -y."
+			fsck -y
+			case $? in
+			0)
+				;;
+			*)
+			echo "Automatic file system check failed; help!"
+				stop_boot
+				;;
+			esac
+		else
+			echo "Automatic file system check failed; help!"
+			stop_boot
+		fi
+		;;
+	12)
+		echo "Boot interrupted."
+		stop_boot
+		;;
+	130)
+		stop_boot
+		;;
+	*)
+		echo "Unknown error; help!"
+		stop_boot
+		;;
+	esac
 }
 
 load_rc_config ${name}
