Add fsck on root file system for 'full' installation.

diff --git a/etc/rc.d/fsck b/etc/rc.d/fsck
--- a/etc/rc.d/fsck
+++ b/etc/rc.d/fsck
@@ -3,6 +3,9 @@
 # $FreeBSD: src/etc/rc.d/fsck,v 1.10.2.2 2008/01/28 08:22:32 dougb Exp $
 #
 # Modified by Volker Theile (votdev@gmx.de)
+# Changes:
+# - Refactor fsck_start to process configured disks only
+# - Add fsck_start_root to check root file system on 'full' installations
 #
 
 # PROVIDE: fsck
@@ -13,8 +16,10 @@
 . /etc/configxml.subr
 
 name="fsck"
+extra_commands="root"
 start_cmd="fsck_start"
 stop_cmd=":"
+root_cmd="fsck_start_root"
 
 fsck_start()
 {
@@ -104,6 +109,59 @@ fsck_start()
 			esac
 		done
 	fi
+}
+
+fsck_start_root()
+{
+	fsck_y_enable=yes
+
+	# During fsck ignore SIGQUIT
+	trap : 3
+
+	echo "Starting root file system check:"
+	fsck -p
+
+	case $? in
+	0)
+		;;
+	2)
+		stop_boot
+		;;
+	4)
+		echo "Rebooting..."
+		reboot
+		echo "Reboot failed; help!"
+		stop_boot
+		;;
+	8)
+		if checkyesno fsck_y_enable; then
+			echo "File system preen failed, trying fsck -y."
+			fsck -y
+			case $? in
+			0)
+				;;
+			*)
+			echo "Automatic file system check failed; help!"
+				stop_boot
+				;;
+			esac
+		else
+			echo "Automatic file system check failed; help!"
+			stop_boot
+		fi
+		;;
+	12)
+		echo "Boot interrupted."
+		stop_boot
+		;;
+	130)
+		stop_boot
+		;;
+	*)
+		echo "Unknown error; help!"
+		stop_boot
+		;;
+	esac
 }
 
 load_rc_config ${name}
