Merge from 9S

diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -1,13 +1,10 @@
 #!/bin/sh
 #
-# $FreeBSD: src/etc/rc.d/nfsd,v 1.13.10.2.2.1 2009/04/15 03:14:26 kensmith Exp $
-#
-# Modified by Volker Theile (votdev@gmx.de)
-# - Add /sbin/ to sysctl calls, otherwise script execution fails via WebGUI.
+# $FreeBSD: stable/9/etc/rc.d/nfsd 223847 2011-07-07 20:59:42Z rmacklem $
 #
 
 # PROVIDE: nfsd
-# REQUIRE: mountd
+# REQUIRE: mountd hostname gssd nfsuserd
 # KEYWORD: nojail shutdown
 # XQUERY: -i "count(//nfsd/enable) > 0" -o "0" -b
 # RCVAR: nfs_server
@@ -23,14 +20,46 @@ command="/usr/sbin/${name}"
 nfs_server_flags=`/usr/local/bin/xml sel -t -v "concat('-u -t -n ',//nfsd/numproc)" ${configxml_file} | /usr/local/bin/xml unesc`
 
 load_rc_config $name
-command_args="${nfs_server_flags}"
 start_precmd="nfsd_precmd"
 sig_stop="USR1"
 
 nfsd_precmd()
 {
-	if ! /sbin/sysctl vfs.nfsrv >/dev/null 2>&1; then
-		force_depend nfsserver || return 1
+	if checkyesno oldnfs_server_enable; then
+		rc_flags="-o ${nfs_server_flags}"
+
+		# Load the module now, so that the vfs.nfsrv sysctl
+		# oids are available.
+		load_kld nfsserver
+
+		if checkyesno nfs_reserved_port_only; then
+			echo 'NFS on reserved port only=YES'
+			/sbin/sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
+		fi
+	else
+		rc_flags="${nfs_server_flags}"
+
+		# Load the modules now, so that the vfs.nfsd sysctl
+		# oids are available.
+		load_kld nfsd
+
+		if checkyesno nfs_reserved_port_only; then
+			echo 'NFS on reserved port only=YES'
+			/sbin/sysctl vfs.nfsd.nfs_privport=1 > /dev/null
+		fi
+
+		if checkyesno nfsv4_server_enable; then
+			if ! checkyesno nfsuserd_enable  && \
+			    ! /etc/rc.d/nfsuserd forcestatus 1>/dev/null 2>&1
+			then
+				if ! force_depend nfsuserd; then
+					err 1 "Cannot run nfsuserd"
+				fi
+			fi
+		else
+			echo 'NFSv4 is disabled'
+			/sbin/sysctl vfs.nfsd.server_max_nfsvers=3 > /dev/null
+		fi
 	fi
 
 	if ! checkyesno rpcbind_enable  && \
@@ -43,11 +72,6 @@ nfsd_precmd()
 	    ! /etc/rc.d/mountd forcestatus 1>/dev/null 2>&1
 	then
 		force_depend mountd || return 1
-	fi
-
-	if checkyesno nfs_reserved_port_only; then
-		echo 'NFS on reserved port only=YES'
-		/sbin/sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
 	fi
 	return 0
 }
