Add /sbin/ to sysctl calls, otherwise script execution fails via WebGUI.

diff --git a/etc/rc.d/nfsd b/etc/rc.d/nfsd
--- a/etc/rc.d/nfsd
+++ b/etc/rc.d/nfsd
@@ -4,6 +4,7 @@
 # $FreeBSD: src/etc/rc.d/nfsd,v 1.13 2004/10/07 13:55:26 mtm Exp $
 #
 # Modified by Volker Theile (votdev@gmx.de)
+# - Add /sbin/ to sysctl calls, otherwise script execution fails via WebGUI.
 #
 
 # PROVIDE: nfsd
@@ -29,7 +30,7 @@ sig_stop="USR1"
 
 nfsd_precmd()
 {
-	if ! sysctl vfs.nfsrv >/dev/null 2>&1; then
+	if ! /sbin/sysctl vfs.nfsrv >/dev/null 2>&1; then
 		force_depend nfsserver || return 1
 	fi
 
@@ -47,7 +48,7 @@ nfsd_precmd()
 
 	if checkyesno nfs_reserved_port_only; then
 		echo 'NFS on reserved port only=YES'
-		sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
+		/sbin/sysctl vfs.nfsrv.nfs_privport=1 > /dev/null
 	fi
 	return 0
 }
