Add ability to configure a disk device as swap device via WebGUI.

diff --git a/etc/rc.d/swap b/etc/rc.d/swap
--- a/etc/rc.d/swap
+++ b/etc/rc.d/swap
@@ -1,5 +1,5 @@
 #!/bin/sh
-# Copyright (c) 2007-2008 Volker Theile (votdev@gmx.de)
+# Copyright (c) 2007-2009 Volker Theile (votdev@gmx.de)
 # All rights reserved.
 #
 # Create a swap file. Usefull for embedded systems.
@@ -8,7 +8,7 @@
 # PROVIDE: swap
 # REQUIRE: FILESYSTEMS
 # KEYWORD: nojail shutdown
-# XQUERY: -i "count(//system/swap_enable) > 0" -o "0" -b
+# XQUERY: -i "count(//system/swap/enable) > 0" -o "0" -b
 # RCVAR: swap
 
 . /etc/rc.subr
@@ -17,6 +17,8 @@
 name="swap"
 rcvar=`set_rcvar`
 
+load_rc_config "${name}"
+
 # Custom commands
 extra_commands="status"
 start_cmd="start_cmd"
@@ -24,18 +26,28 @@ stop_cmd="stop_cmd"
 status_cmd="status_cmd"
 
 # Defaults
-swap_enable="${swap_enable:=NO}"
-mdidfile="/var/run/${name}.mdid"
-swap_mountname=`configxml_get "//system/swap_mountname"`
-swap_file="/mnt/${swap_mountname}/swap_file"
+swap_enable="${swap_enable:-NO}"
+swap_mdidfile=${swap_mdidfile:-"/var/run/${name}.mdid"}
+swap_filename=${swap_filename:-".swapfile"}
+
+# Get type of swap, 'file' or 'device'
+swap_type=`configxml_get "//system/swap/type"`
 
 status_cmd()
 {
-	local _mdid
+	local _mdid _device
 
-	if [ -e ${mdidfile} ]; then
-		_mdid=`cat ${mdidfile}`
-		echo "${name} is running using mdid ${_mdid}."
+	if [ "file" = "${swap_type}" ]; then
+		if [ -e ${swap_mdidfile} ]; then
+			_mdid=`cat ${swap_mdidfile}`
+			_device="/dev/${_mdid}"
+		fi
+	else
+		_device=`configxml_get "//system/swap/devicespecialfile"`
+	fi
+
+	if [ -n "$(pstat -s | grep ${_device})" ]; then
+		echo "${name} is running."
 	else
 		echo "${name} is not running."
 		return 1
@@ -44,60 +56,83 @@ status_cmd()
 
 start_cmd()
 {
-	local _swap_size _mdid
+	local _mdid _uuid _sharename _filename _size _device
 
-	# Check if already running?
-	if [ -e ${mdidfile} ]; then
-		_mdid=`cat ${mdidfile}`
-		echo "${name} already running? (mdid=${_mdid})."
-		return 0
+	if [ "file" = "${swap_type}" ]; then
+		_uuid=`configxml_get "//system/swap/mountpoint"`
+		_sharename=`configxml_get "//mounts/mount[uuid = '${_uuid}']/sharename"`
+		_filename="/mnt/${_sharename}/${swap_filename}"
+
+		# Check if already running
+		if [ -e ${swap_mdidfile} ]; then
+			_mdid=`cat ${swap_mdidfile}`
+			echo "${name} already running? (mdid=${_mdid})."
+			return 0
+		fi
+
+		# Create swap file if necessary
+		if [ ! -e ${_filename} ]; then
+			_size=`configxml_get "//system/swap/size"`
+			/bin/dd if=/dev/zero of=${_filename} bs=1024k count=${_size} >/dev/null 2>&1
+			[ 0 != $? ] && return 1
+			/bin/chmod 0600 ${_filename}
+		fi
+
+		# Create block device
+		_mdid=`/sbin/mdconfig -a -t vnode -f ${_filename}`
+		echo ${_mdid} > ${swap_mdidfile}
+
+		_device="/dev/${_mdid}"
+	else
+		_device=`configxml_get "//system/swap/devicespecialfile"`
 	fi
-
-	echo "Starting ${name}."
-
-	# Create swap file if necessary
-	if [ ! -e ${swap_file} ]; then
-		_swap_size=`configxml_get "//system/swap_size"`
-		/bin/dd if=/dev/zero of=${swap_file} bs=1024k count=${_swap_size} >/dev/null 2>&1
-		[ 0 != $? ] && return 1
-		/bin/chmod 0600 ${swap_file}
-	fi
-
-	# Create block device
-	_mdid=`/sbin/mdconfig -a -t vnode -f ${swap_file}`
-	echo ${_mdid} > ${mdidfile}
 
 	# Enable swap
-	/sbin/swapon "/dev/${_mdid}"
+	echo "Starting ${name}."
+	/sbin/swapon "${_device}"
 }
 
 stop_cmd()
 {
-	local _mdid
+	local _mdid _uuid _sharename _filename _device _result
 
-	# Check if running?
-	if [ ! -e ${mdidfile} ]; then
-		echo "${name} not running? (check ${mdidfile})."
-		return 0
+	if [ "file" = "${swap_type}" ]; then
+		# Check if running?
+		if [ ! -e ${swap_mdidfile} ]; then
+			echo "${name} not running? (check ${swap_mdidfile})."
+			return 0
+		fi
+
+		# Get memory disk id
+		_mdid=`cat ${swap_mdidfile}`
+
+		_device="/dev/${_mdid}"
+	else
+		_device=`configxml_get "//system/swap/devicespecialfile"`
 	fi
 
-	echo "Stopping ${name}."
-
-	# Get memory disk id
-	_mdid=`cat ${mdidfile}`
-
 	# Stop swap
-	/sbin/swapoff "/dev/${_mdid}"
+	echo "Stopping ${name}."
+	/sbin/swapoff "${_device}"
+	_result=$?
 
-	# Destroy block device
-	/sbin/mdconfig -d -u ${_mdid}
+	# Additional action when using swap file
+	if [ "file" = "${swap_type}" ]; then
+		_uuid=`configxml_get "//system/swap/mountpoint"`
+		_sharename=`configxml_get "//mounts/mount[uuid = '${_uuid}']/sharename"`
+		_filename="/mnt/${_sharename}/${swap_filename}"
 
-	# Delete swap file
-	rm -f ${swap_file}
-	
-	# Cleanup
-	rm -f ${mdidfile}
+		# Destroy block device
+		/sbin/mdconfig -d -u ${_mdid}
+
+		# Delete swap file
+		rm -f ${_filename}
+
+		# Cleanup
+		rm -f ${swap_mdidfile}
+	fi
+
+	return ${_result}
 }
 
-load_rc_config ${name}
 run_rc_command "$1"
